config/routes.rb
Rails.application.routes.draw do
  resources :retention_emails do 
    collection do 
      get 'search'
      post 'search'
    end
  end
  resources :recipes
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:user_id, :country, :external, :photo, :published_at)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :external, style: "display: block" %>
    <%= form.text_field :external %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :published_at, style: "display: block" %>
    <%= form.datetime_field :published_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= recipe.country %>
  </p>

  <p>
    <strong>External:</strong>
    <%= recipe.external %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= recipe.photo %>
  </p>

  <p>
    <strong>Published at:</strong>
    <%= recipe.published_at %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>