config/routes.rb
Rails.application.routes.draw do
  resources :retention_emails do 
    collection do 
      get 'search'
      post 'search'
    end
  end
  resources :recipes
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/retention_email.rb
class RetentionEmail < ApplicationRecord
  belongs_to :user
end

app/controllers/retention_emails_controller.rb
class RetentionEmailsController < ApplicationController
  before_action :set_retention_email, only: %i[ show edit update destroy ]

  # GET /retention_emails or /retention_emails.json
  def index
    @retention_emails = RetentionEmail.all
  end


  def search
    @users = []
    # date_from = params[:date_from].present? ? params[:date_from] : nil
    # date_to = params[:date_to].present? ? params[:date_to] : nil

    check_param = validate_range_params(params[:date_from], params[:date_to])

    
    @users = User.find_by_date_ranges(check_param[:date_from], check_param[:date_to]) if check_param[:valid]
    

    if request.post?
      if check_param[:valid]
        if is_search_click?
          redirect_to search_retention_emails_path(date_from: check_param[:date_from], date_to: check_param[:date_to])
        elsif is_send_click?
          @users = User.find_by_date_ranges(check_param[:date_from], check_param[:date_to])
          @users.each do |user|
            user.create_reten_email_record(params[:body], check_param[:date_from], check_param[:date_to])
          end

        end
      else
        flash.now[:notice] = check_param[:message]
        redirect_to search_retention_emails_path(date_from: params[:date_from], date_to: params[:date_to])
      end
      
    end

    
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv, filename: "author-retention-users-#{Time.zone.today}.csv" }
    end
  end

  # GET /retention_emails/1 or /retention_emails/1.json
  def show
  end

  # GET /retention_emails/new
  def new
    @retention_email = RetentionEmail.new
  end

  # GET /retention_emails/1/edit
  def edit
  end

  # POST /retention_emails or /retention_emails.json
  def create
    @retention_email = RetentionEmail.new(retention_email_params)

    respond_to do |format|
      if @retention_email.save
        format.html { redirect_to retention_email_url(@retention_email), notice: "Retention email was successfully created." }
        format.json { render :show, status: :created, location: @retention_email }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @retention_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retention_emails/1 or /retention_emails/1.json
  def update
    respond_to do |format|
      if @retention_email.update(retention_email_params)
        format.html { redirect_to retention_email_url(@retention_email), notice: "Retention email was successfully updated." }
        format.json { render :show, status: :ok, location: @retention_email }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @retention_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retention_emails/1 or /retention_emails/1.json
  def destroy
    @retention_email.destroy

    respond_to do |format|
      format.html { redirect_to retention_emails_url, notice: "Retention email was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retention_email
      @retention_email = RetentionEmail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def retention_email_params
      params.require(:retention_email).permit(:body, :date_from, :date_to)
    end

    def is_search_click?
      params[:commit] == "Search"
    end

    def is_send_click?
      params[:commit] == "Send"
    end

    def validate_range_params(from_param, to_param)
      date_from = parse_date(from_param)
      date_to = parse_date(to_param)

      return_obj = {
        date_from: date_from,
        date_to: date_to,
        valid: false
      }

      if date_from.present? && date_to.present?
        if date_from < date_to
          return_obj.merge!(messge: "Okay", valid: true)
        else
          return_obj.merge!(messge: "Start date should be greater than from date.")
        end
      elsif !date_from.present? && date_to.present?
        return_obj.merge!(messge: "From date required!")
      elsif date_from.present? && !date_to.present?
        return_obj.merge!(messge: "End date required!")
      else
        return_obj.merge!(messge: "Invalid Params")
      end

      return_obj
    end

    def parse_date(param_date)
      return nil unless param_date.present?
      date_obj = Date.parse(param_date) rescue nil 
      date_obj = nil unless (date_obj.is_a?(Date) || date_obj.is_a?(Time))
      date_obj
    end
end

app/helpers/retention_emails_helper.rb
module RetentionEmailsHelper
end

app/views/retention_emails/_form.html.erb
<%= form_with(model: retention_email) do |form| %>
  <% if retention_email.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(retention_email.errors.count, "error") %> prohibited this retention_email from being saved:</h2>

      <ul>
        <% retention_email.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :date_from, style: "display: block" %>
    <%= form.date_field :date_from %>
  </div>

  <div>
    <%= form.label :date_to, style: "display: block" %>
    <%= form.date_field :date_to %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/retention_emails/_retention_email.html.erb
<div id="<%= dom_id retention_email %>">
  <p>
    <strong>Body:</strong>
    <%= retention_email.body %>
  </p>

  <p>
    <strong>Date from:</strong>
    <%= retention_email.date_from %>
  </p>

  <p>
    <strong>Date to:</strong>
    <%= retention_email.date_to %>
  </p>

</div>

app/views/retention_emails/edit.html.erb
<h1>Editing retention email</h1>

<%= render "form", retention_email: @retention_email %>

<br>

<div>
  <%= link_to "Show this retention email", @retention_email %> |
  <%= link_to "Back to retention emails", retention_emails_path %>
</div>

app/views/retention_emails/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Retention emails</h1>

<div id="retention_emails">
  <% @retention_emails.each do |retention_email| %>
    <%= render retention_email %>
    <p>
      <%= link_to "Show this retention email", retention_email %>
    </p>
  <% end %>
</div>

<%= link_to "New retention email", new_retention_email_path %>

app/views/retention_emails/new.html.erb
<h1>New retention email</h1>

<%= render "form", retention_email: @retention_email %>

<br>

<div>
  <%= link_to "Back to retention emails", retention_emails_path %>
</div>

app/views/retention_emails/search.html.erb
<p style="color: green"><%= notice %></p>

<% flash.each do |type, msg| %>
  <div>
    <p><%= msg %></p>
  </div>
<% end %>

<h1>Retention emails</h1>

<%= form_tag search_retention_emails_path, method: 'POST' do %>
<p>
  <%= date_field_tag :date_from, (params[:date_from].present? ? Date.parse(params[:date_from]) : nil rescue nil ), placeholder: 'Date From' %>
</p>

<p>
  <%= date_field_tag :date_to, (params[:date_to].present? ? Date.parse(params[:date_to]) : nil rescue nil ), placeholder: 'Date From' %>
</p>

<%= submit_tag 'Send' %><br />
<%= submit_tag 'Search' %>

<% end %>

<%= link_to 'Download', search_retention_emails_path(format: 'csv', params: request.params) %>

<div id="retention_emails">

  <table style="border:1px solid black">
  <tr>
    <td>Name</td><td>Email</td><td>Published</td>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.recipes.first.published_at %></td>
  </tr>
    
    
    
  <% end %>
  </table>
</div>

app/views/retention_emails/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @retention_email %>

<div>
  <%= link_to "Edit this retention email", edit_retention_email_path(@retention_email) %> |
  <%= link_to "Back to retention emails", retention_emails_path %>

  <%= button_to "Destroy this retention email", @retention_email, method: :delete %>
</div>